coverage:
  range: 70..90
  status:
    project:
      default:
        target: auto
        threshold: 5%

fixes:
  - "/home/runner/work/fourdvarjax/fourdvarjax/::"

ignore:
  - "setup.py"
  - "*/tests/.*"
  - "__init__.py"
  - "tests/*.py"
